name: Publish Sphinx Site

on: push

jobs:
  deploy-ghpages:
    runs-on: ubuntu-latest
    strategy:
      #max-parallel: 3
      matrix:
        python-version: [3.8]
      fail-fast: false

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      #- name: Set up Node ğŸ§¶
      #uses: actions/setup-node@v2-beta
      #with:
      #node-version: "12"
      - name: Set up Python ${{ matrix.python-version }} ğŸ
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build ğŸ”¨
        run: |
          pip install -r _site/requirements.txt
          #yarn
          make html
      - name: Prepare deployment âŒ›
        run: |
          # fetch all branches
          git fetch --depth=1
          git checkout gh-pages
          rm -rf site
          mv _build site
      - name: Deploy ğŸš€
        uses: EndBug/add-and-commit@v4.4.0
        with:
          message: "Currently deploying: ${{ github.ref }}"
          ref: "gh-pages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
