name: Publish Gollum Wiki

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["2.6"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Build with ugollum-site'
        run: |
          gem install bundler
          bundle config path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
          bundle exec gollum-site generate
          ls -Rl
